CREATE DATABASE IF NOT EXISTS PROJETO3CAMADAS;
USE PROJETO3CAMADAS;
drop table usuario;
CREATE TABLE USUARIO(
ID INT NOT NULL auto_increment,
EMAIL VARCHAR(150) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
) ENGINE=InnoDB; 


drop table postagens;
CREATE TABLE POSTAGENS(
ID INT NOT NULL auto_increment,
LEGENDA VARCHAR(150) NOT NULL,
LOCAl_postagem VARCHAR(150) NOT NULL,
PRIMARY KEY (ID)
)ENGINE=InnoDB;

INSERT INTO `PROJETO3CAMADAS`.`usuario` (`ID`, `EMAIL`, `SENHA`) VALUES
(1, 'julio@gmail', 'teste'),
(2, 'julio@gmail', 'teste');  